version: '2'
services:
    security-app:
        image: security
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://security-mysql:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    security-mysql:
        extends:
            file: mysql.yml
            service: security-mysql
